services:
  sf2-harness:
    build: .
    image: sf2-harness:latest
    container_name: sf2-harness
    environment:
      - ANDROID_SERIAL=host.docker.internal:5555
      - ADB_PATH=/usr/bin/adb
      - ADB_CONNECT=host.docker.internal:5555
      - FRIDA_HOST=host.docker.internal
      - FRIDA_PORT=27042
      - FRIDA_DIRECT=0
    stdin_open: true
    tty: true